web/router.ex
defmodule SunsetPickleball.Router do
  use SunsetPickleball.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SunsetPickleball do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/players", PlayerController
    get "/groups/generate", GroupController, :generate
    post "/groups/generate", GroupController, :generate_groups
    resources "/groups", GroupController
    resources "/games", GameController
    resources "/scores", ScoreController
    resources "/earned_points_ratios", EarnedPointsRatioController
  end
end

web/views/layout_view.ex
defmodule SunsetPickleball.LayoutView do
  use SunsetPickleball.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pickleball league management and statistics">
    <meta name="author" content="Taylor O'Brien">

    <title>Sunset Pickleball</title>
    <link rel="stylesheet" href=<%= static_path(@conn, "/css/app.css") %>>
    <link rel="icon" type="image/png" href=<%= static_path(@conn, "/images/logo.png") %>>
  </head>

  <body>
    <div class="container-fluid">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href=<%= page_path(@conn, :index) %>>Home</a></li>
            <li><a href=<%= player_path(@conn, :index) %>>Players</a></li>
            <li><a href=<%= group_path(@conn, :index) %>>Groups</a></li>
            <li><a href=<%= game_path(@conn, :index) %>>Games</a></li>
          </ul>
        </nav>
        <span class="text-logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/scoreboard.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pickleball league management and statistics">
    <meta name="author" content="Taylor O'Brien">

    <title>Sunset Pickleball</title>
    <link rel="stylesheet" href=<%= static_path(@conn, "/css/app.css") %>>
    <link rel="icon" type="image/png" href=<%= static_path(@conn, "/images/logo.png") %>>
  </head>

  <body class="scoreboard-body">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>